name: junkjar
description: Final year project
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  barcode_scan: ^2.0.1
  cupertino_icons: ^0.1.3
  cloud_firestore: ^0.13.4+2
  gradient_widgets: ^0.5.2
  google_fonts: ^0.3.10
  flare_flutter: ^2.0.1
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.3.0
  flutter_signin_button: ^1.0.0
  shared_preferences: ^0.5.6+3
  uuid: ^2.0.4
  google_maps_flutter: ^0.5.25+2
  geolocator: ^5.3.0
  url_launcher: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/